# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='courseNum',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='department',
            field=models.CharField(default='cmpt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='semester',
            field=models.CharField(default='fall', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
    ]
