# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20170726_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.TextField()),
                ('department', models.TextField()),
                ('courseNum', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='year',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='courseCampus',
            field=models.TextField(default='Burnaby'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='courseDays',
            field=models.TextField(default='Mo,We,Fr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='courseEndTime',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='courseExamTime',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='courseRoom',
            field=models.TextField(default='C9001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='courseStarTime',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='department',
            field=models.TextField(),
        ),
    ]
